language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
env:
  - HAPI=hapi@18
before_script:
  - npm install --save-dev $HAPI
after_script:
  - 'npm run test:cov:coveralls'
